services:
  mariadb:
    image: mariadb:11.3 # You can specify the latest stable version
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor # MariaDB uses MARIADB_ instead of MYSQL_
      MARIADB_DATABASE: gallery
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mariadb # Match the service name
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mariadb_data:
